apiVersion: 1

deleteDatasources:
 - name: Prometheus
   orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  url: 'http://prometheus:9090'
  access: proxy
  editable: true
  is_default: true
  org_id: 1
  version: 1     
